title: Manav Portfolio
description: Always excited to extract insights from data that bring value to business
google_analytics:
theme: jekyll-theme-hacker
github:
  zip_url: https://github.com/Manav-56
